ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/tase_noam/hello-app'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  params:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

liveness:
  params:
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

test: Healthy22